// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flkzorytgcunnyhzcpfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsa3pvcnl0Z2N1bm55aHpjcGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODkzOTQsImV4cCI6MjA2Njg2NTM5NH0.0hp_Dk_2DUw8ZcaXTIMkVk4pRdKm7bpa0wFdMwlqcZ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});